<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MNAYAK2L3" name="com.hellofresh.challenge.WebTest" tests="4" failures="1" timestamp="20 Sep 2019 09:59:13 GMT" time="71.078" errors="0">
  <testcase name="signIn" time="18.958" classname="com.hellofresh.challenge.WebTest"/>
  <testcase name="logInTest" time="12.750" classname="com.hellofresh.challenge.WebTest"/>
  <testcase name="failedlogInTest" time="12.442" classname="com.hellofresh.challenge.WebTest">
    <failure type="java.lang.AssertionError" message="Fail ::TC failed">
      <![CDATA[java.lang.AssertionError: Fail ::TC failed
at org.testng.Assert.fail(Assert.java:96)
at com.hellofresh.driver.DriverManager.logReport(DriverManager.java:93)
at com.hellofresh.challenge.WebTest.failedlogInTest(WebTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- failedlogInTest -->
  <testcase name="checkoutTest" time="26.928" classname="com.hellofresh.challenge.WebTest"/>
</testsuite> <!-- com.hellofresh.challenge.WebTest -->
